version: '3.7'
services:
     postgres:
        image: postgres
        environment:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: calculator-db
        volumes:
          - ./pgdata:/var/lib/posgresql/data
        ports:
          - "5432:5432"
    #  api:
    #     container_name: aritmetic-api
    #     build:
    #         context: ./backend
    #         dockerfile: Dockerfile
    #     ports:
    #       - "3000:3000"
    #     volumes:
    #           - .:/usr/app/
    #           - .:/usr/app/node_modules
    #     env_file:
    #           - ./backend/.env
    #     depends_on:
    #         - postgres
    