version: '3.7'
services:
     postgres:
        image: postgres
        environment:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: calculator-db
        volumes:
          - ./pgdata:/var/lib/posgresql/data
        ports:
          - '5432:5432'
    #  api:
    #     container_name: aritmetic-api
    #     build:
    #         context: .
    #         dockerfile: ./backend/Dockerfile
    #         # target: development
    #     volumes:
    #           - .:/usr/app/
    #           - /usr/app/node_modules
    #     env_file:
    #           - ./backend/.env
    #     environment:
    #           NODE_ENV: development
    #           DB_HOST: localhost
    #           DB_USER: postgres
    #           DB_PASSWORD: postgres
    #           DB_PORT: 5432
    #           DB_NAME: calculator-db
    #           APP_PORT: 3000
    #           JWT_KEY: 12345abcde
    #     depends_on:
    #         - postgres
    