version: '3.7'
services:
     api:
        container_name: aritmetic-api
        build:
            context: ./backend
            dockerfile: Dockerfile
        links:
          - "db:database"
        ports:
          - "3000:80"
        volumes:
              - .:/usr/app/
              - .:/usr/app/node_modules
        env_file:
              - ./backend/.env
        environment: 
          DB_HOST: db
        depends_on:
            - db
        command: npm run dev
     db:
        image: postgres
        environment:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: calculator-db
        volumes:
          - ./pgdata:/var/lib/posgresql/data
        ports:
          - "5432:5432"