name: Build and Test

on:
  push:
    branches: [ "master" ]
    paths:
      - './backend'
  pull_request:
    branches: [ "master" ]
    paths:
      - './backend'

defaults:
      run:
        working-directory: ./backend
jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: cd ./backend && npm ci
    - run: cd ./backend && npm run build --if-present
    - run: cd ./backend && npm test
